export const images = [
  '/images/product-1.jpg',
  '/images/product-2.jpg',
  '/images/product-3.jpg',
  '/images/product-4.jpg',
  '/images/product-5.jpg',
  '/images/product-6.jpg',
  '/images/product-7.jpg',
  '/images/product-2.jpg',
];

export const slides = [
  {
    id: 1,
    image: "/images/banner/banner-3.png",
    title: "Faith Meets Fashion",
    subtitle: "A perfect blend of contemporary design and timeless modesty.",
  },
  {
    id: 2,
    image: "/images/banner/banner-2.png",
    title: "Grace in Every Step",
    subtitle: "Experience comfort, confidence, and elegance in every abaya.",
  },
  {
    id: 3,
    image: "/images/banner/banner-1.png",
    title: "Embrace Your Journey",
    subtitle: "Wear your faith beautifully with our handcrafted abaya styles.",
  },
];


export const videos = [
  {
    id: 1,
    url: 'https://www.facebook.com/reel/3087933404712855/',
    iframe: `https://www.facebook.com/plugins/video.php?height=476&href=https%3A%2F%2Fwww.facebook.com%2Freel%2F3087933404712855%2F&show_text=false&width=267&t=0&autoplay=true&mute=1&loop=true`,
    username: '@faithjourney',
    likes: '1.2K',
    comments: '230',
    shares: '80',
  },
  {
    id: 2,
    url: 'https://www.facebook.com/reel/3650327968430482/',
    iframe: `https://www.facebook.com/plugins/video.php?height=476&href=https%3A%2F%2Fwww.facebook.com%2Freel%2F3650327968430482%2F&show_text=false&width=267&t=0&autoplay=true&mute=1&loop=true`,
    username: '@faithjourney',
    likes: '950',
    comments: '120',
    shares: '60',
  },
  {
    id: 3,
    url: 'https://www.facebook.com/reel/2210782086110657/',
    iframe: `https://www.facebook.com/plugins/video.php?height=476&href=https%3A%2F%2Fwww.facebook.com%2Freel%2F2210782086110657%2F&show_text=false&width=267&t=0&autoplay=true&mute=1&loop=true`,
    username: '@faithjourney',
    likes: '560',
    comments: '70',
    shares: '25',
  },
  {
    id: 4,
    url: 'https://www.facebook.com/reel/685991903859388/',
    iframe: `https://www.facebook.com/plugins/video.php?height=476&href=https%3A%2F%2Fwww.facebook.com%2Freel%2F685991903859388%2F&show_text=false&width=267&t=0&autoplay=true&mute=1&loop=true`,
    username: '@faithjourney',
    likes: '1.8K',
    comments: '310',
    shares: '120',
  },
  {
    id: 5,
    url: 'https://www.facebook.com/reel/2210782086110657/',
    iframe: `https://www.facebook.com/plugins/video.php?height=476&href=https%3A%2F%2Fwww.facebook.com%2Freel%2F2210782086110657%2F&show_text=false&width=267&t=0&autoplay=true&mute=1&loop=true`,
    username: '@faithjourney',
    likes: '560',
    comments: '70',
    shares: '25',
  },
];

export const reviewImages = [
  '/images/review-1.jpg',
  '/images/review-2.jpg',
  '/images/review-3.jpg',
  '/images/review-4.jpg',
  '/images/review-5.jpg',
  '/images/review-6.jpg',
  '/images/review-7.jpg',
];

export const defaultCheckoutForm = {
  fullName: '',
  phoneNumber: '',
  shippingAddress: { address: '', area: '', zone_id: 0 },
  billingAddress: { address: '', area: '', zone_id: 0 },
  sameAsShipping: false,
  deliveryCharge: 100,
  paymentMethod: 'delivery',
  notes: '',
  agreeToTerms: false,
};






[
  {
    id: 1,
    slug: 'classic-chiffon-embroidery-abaya-black',
    product_code: 'ABAYA-101',
    thumbnail_url: 'https://borka-asset.tanzid.site/product-images/1.webp',
    original_price: '1800.00',
    discount_type: 'percentage',
    discount_value: '15.00',
    is_discount_active: 1,
    color_name: 'Black',
    color_id: 1,
    main_category_id: 3,
    category_id: 18,
    product_label: 'Classic Chiffon Embroidery Abaya (Black)',
    product_category: 'Abaya - Premium Collection',
    sale_price: '1530.00',
    discount_amount: '270.00',
    discount_label: '15%',
  },
  {
    id: 2,
    slug: 'premium-khimar-double-layer-maroon',
    product_code: 'KHIMAR-202',
    thumbnail_url: 'https://borka-asset.tanzid.site/product-images/2.webp',
    original_price: '1200.00',
    discount_type: 'fixed',
    discount_value: '150.00',
    is_discount_active: 1,
    color_name: 'Maroon',
    color_id: 5,
    main_category_id: 2,
    category_id: 10,
    product_label: 'Premium Double Layer Khimar (Maroon)',
    product_category: 'Khimar - Double Layer',
    sale_price: '1050.00',
    discount_amount: '150.00',
    discount_label: '৳150 Off',
  },
  {
    id: 3,
    slug: 'butterfly-khimar-navy-blue',
    product_code: 'KHIMAR-303',
    thumbnail_url: 'https://borka-asset.tanzid.site/product-images/3.webp',
    original_price: '950.00',
    discount_type: 'percentage',
    discount_value: '5.00',
    is_discount_active: 1,
    color_name: 'Navy Blue',
    color_id: 4,
    main_category_id: 2,
    category_id: 9,
    product_label: 'Butterfly Style Khimar (Navy Blue)',
    product_category: 'Khimar - Butterfly Collection',
    sale_price: '902.50',
    discount_amount: '47.50',
    discount_label: '5%',
  },
  {
    id: 4,
    slug: 'cover-up-chiffon-dehra-embroidery-abaya-blue',
    product_code: 'COVER-UP-002',
    thumbnail_url:
      'https://borka-asset.tanzid.site/product-images/6925683db8385.webp',
    original_price: '1000.00',
    discount_type: 'percentage',
    discount_value: '10.00',
    is_discount_active: 1,
    color_name: 'Blue',
    color_id: 4,
    main_category_id: 3,
    category_id: 19,
    product_label: 'Cover Up Chiffon (Blue)',
    product_category: 'Tops/Kurti - Dehra Embroidery Abaya',
    sale_price: '900.00',
    discount_amount: '100.00',
    discount_label: '10%',
  },
  {
    id: 5,
    slug: 'saudi-nida-umbrella-abaya-brown',
    product_code: 'ABAYA-505',
    thumbnail_url: 'https://borka-asset.tanzid.site/product-images/5.webp',
    original_price: '2200.00',
    discount_type: 'percentage',
    discount_value: '20.00',
    is_discount_active: 1,
    color_name: 'Brown',
    color_id: 3,
    main_category_id: 3,
    category_id: 20,
    product_label: 'Saudi Nida Umbrella Abaya (Brown)',
    product_category: 'Abaya - Saudi Nida',
    sale_price: '1760.00',
    discount_amount: '440.00',
    discount_label: '20%',
  },
  {
    id: 6,
    slug: 'japan-silk-khimar-light-pink',
    product_code: 'KHIMAR-606',
    thumbnail_url: 'https://borka-asset.tanzid.site/product-images/6.webp',
    original_price: '1400.00',
    discount_type: 'fixed',
    discount_value: '200.00',
    is_discount_active: 1,
    color_name: 'Light Pink',
    color_id: 6,
    main_category_id: 2,
    category_id: 11,
    product_label: 'Japan Silk Khimar (Light Pink)',
    product_category: 'Khimar - Japan Silk',
    sale_price: '1200.00',
    discount_amount: '200.00',
    discount_label: '৳200 Off',
  },
  {
    id: 7,
    slug: 'butterfly-abaya-olive-green',
    product_code: 'ABAYA-707',
    thumbnail_url: 'https://borka-asset.tanzid.site/product-images/7.webp',
    original_price: '1900.00',
    discount_type: 'percentage',
    discount_value: '12.00',
    is_discount_active: 1,
    color_name: 'Olive Green',
    color_id: 7,
    main_category_id: 3,
    category_id: 21,
    product_label: 'Butterfly Abaya (Olive Green)',
    product_category: 'Abaya - Butterfly Collection',
    sale_price: '1672.00',
    discount_amount: '228.00',
    discount_label: '12%',
  },
  {
    id: 8,
    slug: 'pleated-khimar-deep-purple',
    product_code: 'KHIMAR-808',
    thumbnail_url: 'https://borka-asset.tanzid.site/product-images/8.webp',
    original_price: '1100.00',
    discount_type: 'percentage',
    discount_value: '8.00',
    is_discount_active: 1,
    color_name: 'Deep Purple',
    color_id: 8,
    main_category_id: 2,
    category_id: 12,
    product_label: 'Pleated Khimar (Deep Purple)',
    product_category: 'Khimar - Pleated Style',
    sale_price: '1012.00',
    discount_amount: '88.00',
    discount_label: '8%',
  },
];
